# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os:
  - linux
  - osx

language: R

sudo: false

cache: packages

script:
- R CMD build .
- R CMD check *tar.gz

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p ~/.R && echo "SHLIB_OPENMP_CXXFLAGS = " >>~/.R/Makevars; fi